apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-connector-scheduled
  namespace: openmetadata
  labels:
    app: s3-connector
    component: scheduled-ingestion
    version: v0.9
spec:
  # Schedule: Run every 6 hours
  schedule: "0 */6 * * *"
  
  # Job management
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  # Prevent overlapping jobs
  startingDeadlineSeconds: 300  # Job must start within 5 minutes
  
  jobTemplate:
    metadata:
      labels:
        app: s3-connector
        component: scheduled-ingestion
    spec:
      # Job completion settings
      completions: 1
      parallelism: 1
      backoffLimit: 2
      activeDeadlineSeconds: 3600  # Job timeout: 1 hour
      
      template:
        metadata:
          labels:
            app: s3-connector
            component: scheduled-ingestion
            version: v0.9
        spec:
          serviceAccountName: s3-connector-sa
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          
          containers:
          - name: s3-connector
            image: your-registry/s3-connector:v0.9  # Replace with your image
            imagePullPolicy: Always
            
            # Resource management for scheduled jobs
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            
            # Environment variables
            env:
            - name: OPENMETADATA_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: s3-connector-secrets
                  key: openmetadata-server-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-connector-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-connector-secrets
                  key: aws-secret-access-key
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-connector-secrets
                  key: bucket-name
            - name: PYTHONPATH
              value: "/app/src:${PYTHONPATH}"
            - name: CONNECTOR_TYPE
              value: "s3"
            - name: JOB_TYPE
              value: "scheduled"
            
            # Volume mounts
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
            
            # Security context
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            
            # Command for scheduled ingestion
            command: ["metadata"]
            args: 
            - "ingest"
            - "-c"
            - "/app/config/ingestion-config.yaml"
            - "--verbose"
          
          # Volumes
          volumes:
          - name: config-volume
            configMap:
              name: s3-connector-config
          - name: tmp-volume
            emptyDir: {}
          
          # Pod settings
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 60
