apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-connector-sa
  namespace: openmetadata
  labels:
    app: s3-connector
    component: service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3-connector-role
  namespace: openmetadata
rules:
# Allow reading configmaps and secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
# Allow reading pods for self-monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Allow creating events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3-connector-rolebinding
  namespace: openmetadata
subjects:
- kind: ServiceAccount
  name: s3-connector-sa
  namespace: openmetadata
roleRef:
  kind: Role
  name: s3-connector-role
  apiGroup: rbac.authorization.k8s.io
